[package]
name = "skill_lab"
version = "0.1.0"
authors = ["Chssam"]
edition = "2024"
publish = false


[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
strip = true
incremental = false

[profile.dev]
debug = 0

[profile.dev.build-override]
opt-level = 3
codegen-units = 1


[features]
default = ["web"]
web = ["dioxus/web", "dioxus-motion/web", "dioxus-motion/transitions"]
desktop = [
    "dioxus/desktop",
    "dioxus-motion/desktop",
    "dioxus-motion/transitions",
]
mobile = ["dioxus/mobile", "dioxus-motion/desktop", "dioxus-motion/transitions"]

[dependencies]
dioxus = { version = "=0.7.8", features = ["router"] }
dioxus-icons = { version = "0.1.0", default-features = false }
dioxus-motion = { version = "0.3.5", optional = true, default-features = false }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }

bevy_time = { version = "0.18", default-features = false, features = [
    "std",
    "bevy_reflect",
] }
bevy_ecs = "0.18"
bevy_derive = "0.18"
bevy_reflect = "0.18"
bevy_math = { version = "0.18", default-features = false, features = [
    "std",
    "bevy_reflect",
] }
bevy_scene = "0.18"

web-sys = { version = "0.3.99", features = [
    "Storage",
    "HtmlElement",
    "HtmlDocument",
    "HtmlImageElement",
    "IdbFactory",
    "Window",
    "Element",
    "Document",
    "DomRect",
] }
regex = "1.11.3"
tokio = "1.48"
getrandom = { version = "0.4.2", features = ["wasm_js"] }
web-time = "1.1.0"
async-std = "1.13.2"

chrono = "0.4.44"
easer = "0.3"
strum = { version = "0.28", features = ["derive"] }
convert_case = "0.11"
ron = "0.12"
serde = "1.0"
time = { version = "0.3.44", default-features = false }


[dev-dependencies]
dioxus-ssr = "=0.7.8"
